# Generated by Django 6.0.1 on 2026-05-21 10:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('floors', models.IntegerField()),
                ('height', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('visitedAt', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=25830)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('visitedAt', models.DateTimeField()),
                ('rating', models.IntegerField(default=0.0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=25830)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('length', models.FloatField()),
                ('lanes', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=100)),
                ('visitedAt', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=25830)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
